### ISSUE TITLE
Authenticated Users

### ISSUE THREAD

**Issue by MattGibney** [MattGibney/JobBoard#22]
### Acceptance Criteria
* Login form requiring a username and password
* Successful login attempt results in a session that is valid for 8 hours
* A dashboard page that can only be accessed by authenticated users
* Passwords are stored as hashes

### Out of scope
* Registration system, administrators can only be created by other admins
* The first admin needs to be manually created

**Comment by Moppler** [comment]
Fixed in recent merge of #35
