### ISSUE TITLE
Date shown incorrectly on job board front end

### ISSUE THREAD

**Issue by jwpf100** [MattGibney/JobBoard#24]
![image](https://user-images.githubusercontent.com/64267174/99374282-54ffa400-28ba-11eb-8525-6e1797b5fb5a.png)

The date is shown incorrectly on the job board main page (route '/').  It is a series of numbers rather than dd/mm/yyyy or similar format.

### Acceptance Criteria

- Display date in format dd/mm/yyyy

**Comment by MattGibney** [comment]
It would be ideal if it's in the same format as the `/job/:jobId` route. That would make it consistent.
