### ISSUE TITLE
List of jobs

### ISSUE THREAD

**Issue by MattGibney** [MattGibney/JobBoard#3]
### User Story
As a job seeker, when visiting the application. I would like to see a list of all jobs currently live on the platform. They should be ordered newest to oldest. Each job advert should have the following information:
* Job Title
* Location
* Salary
* Job Type
* Summary
* Date posted

### Acceptance Criteria
* Jobs listed in order newest first.
* Jobs are visually distinct from one another (Doesn't have to be particularly pretty at this stage)
* Jobs display all of the required information listed above in the user story.

**Comment by MattGibney** [comment]
There is nothing in this story that suggests that the jobs need to be dynamically loaded in from somewhere.

I will implement this story with a Hardcoded list of jobs. These can later be moved to persistent storage in a new story.

**Comment by jwpf100** [comment]
Should the job board be showing date posted as per the acceptance criteria?

**Comment by MattGibney** [comment]
It would be better to raise a Bug and submit a Pull Request.
